### ISSUE TITLE
issue with gdrive url format in fstab

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-content-proxy#181]
it looks like a google changed their format slightly omitting the `/u/0` in the URLs, not sure if that trips anything up... but a `?sharing` at the end of the URL also seems to trip up the folder id extraction.

should be a lot more robust as this is usually one of the first steps in a helix journey.

**Comment by trieloff** [comment]
Here is a related trace: https://app.epsagon.com/spans/0e90c07c-573f-df12-0129-e660fb928159?tab=graph

**Comment by trieloff** [comment]
See https://github.com/orangegloves/helixtest/commits/master/fstab.yaml for a history of two failing configs and one that is working.

**Comment by tripodsan** [comment]
you can always use the canonical form:

```
gdrive:103zROBvlcykzED4w0izXXhWkN0o9HD55
```
