### ISSUE TITLE
ERR_HTTP2_INVALID_SESSION when proxying against other runtime actions

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#196]
**Description**
during a recent outage, non of the invocations to content proxy was able to deliver content, if it was fetching it from another runtime action. the error was:

```
Unhandled error Error [ERR_HTTP2_INVALID_SESSION]: The session has been destroyed at ClientHttp2Session.request (internal/http2/core.js:1558:13)
```

The proxy requests to github still worked.

During the same time, Adobe I/O Runtime changed some routing of their traffic. 

---

After forcing HTTP1 and redeploying the action, everything worked again normally. Interestingly, deploying another version with http2 still enabled also worked. also, requesting older versions e.g. 2.0.7 also works now.

also, before the deployment with http2 disabled, I never tried to invoke the content proxy directly, the errors were only observed in coralogix. so it might well be, that it worked before invoking the action directly with curl (and not via fastly)

also, looking at the activations, there were many cold starts, which I assume rules out any problems in caches inside the nodejs process. My wildest guess is, that some network information (dns, route, cert) somehow changed but wasn't updated in the cache of the container environment and caused problems establishing the http2 session....

---

Unfortunately, it's not possible to reproduce the issue. there was a similar behaviour in helix-static and the typekit fonts: https://github.com/adobe/helix-static/issues/351

/cc @stefan-guggisberg @tysonnorris

**Comment by tripodsan** [comment]
As @tysonnorris pointed out, the current runtime doesn't support http/2, but the azure endpoint does:

```
$ curl -i --http2  https://adobeioruntime.net/api/v1
HTTP/1.1 200 OK
Access-Control-Allow-Headers: Authorization, Origin, X-Requested-With, Content-Type, Accept, User-Agent
Access-Control-Allow-Methods: GET, DELETE, POST, PUT, HEAD
Access-Control-Allow-Origin: *
Content-Type: application/json
Date: Thu, 29 Oct 2020 03:31:36 GMT
Strict-Transport-Security: max-age=7884000; includeSubDomains
X-Request-ID: UVpM2Obaddd6P72OEVGAmYmDlbxdf9EK
Content-Length: 197
Connection: keep-alive

{"api_version":"1.0.0","api_version_path":"v1","build":"2020-10-27 - a","buildno":"reftags/master - v69-4751bc4","description":"OpenWhisk API","swagger_paths":{"api-docs":"/api-docs","ui":"/docs"}}
$ curl -i --http2  https://azure-adobeioruntime.net/api/v1
HTTP/2 200
content-length: 184
content-type: application/json
x-request-id: udjEbMWoc9Q06291d7DAdE6fQRGpj4Y5
access-control-allow-origin: *
access-control-allow-headers: Authorization, Origin, X-Requested-With, Content-Type, Accept, User-Agent
access-control-allow-methods: GET, DELETE, POST, PUT, HEAD
strict-transport-security: max-age=7884000; includeSubDomains
x-envoy-upstream-service-time: 3
x-azure-ref: 0ozeaXwAAAACH1azPF+MMTK+FdLyY4py0VFlPMDFFREdFMDUyMABkZTE4N2MxMS1jNWE5LTQ3MjMtYTFjYy04NWMxZmQxZTM5Nzc=
date: Thu, 29 Oct 2020 03:31:47 GMT

{"api_version":"1.0.0","api_version_path":"v1","build":"2019-04-05-18:03:02Z","buildno":"20190405a","description":"OpenWhisk API","swagger_paths":{"api-docs":"/api-docs","ui":"/docs"}}
```

Also, `rawgithub` doesn't support http/2:

```
$ curl -i --http2  https://raw.githubusercontent.com/davidnuescheler/n2/master/fstab.yaml
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 94
Content-Type: text/plain; charset=utf-8
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
ETag: "64d7c7ada10577d1c18bd4b67f1563df877050a8c642e1423634d57c4c74e6b6"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
Via: 1.1 varnish (Varnish/6.0), 1.1 varnish
X-GitHub-Request-Id: 095C:0B2C:C1BAD:D1A19:5F9A373D
Accept-Ranges: bytes
Date: Thu, 29 Oct 2020 03:32:11 GMT
X-Served-By: cache-tyo19937-TYO
X-Cache: MISS, HIT
X-Cache-Hits: 0, 1
X-Timer: S1603942332.573362,VS0,VE1
Vary: Authorization,Accept-Encoding, Accept-Encoding
Access-Control-Allow-Origin: *
X-Fastly-Request-ID: f6e4d03506d127e9a1ad1e811bd120afa00eda8f
Expires: Thu, 29 Oct 2020 03:37:11 GMT
Source-Age: 126

mountpoints:
  /: https://drive.google.com/drive/u/0/folders/1rU1Jy7iaRycx87k4ndW7I338iPP03TvM
```

**Comment by stefan-guggisberg** [comment]
> As @tysonnorris pointed out, the current runtime doesn't support http/2, but the azure endpoint does:

But we're not using the azure endpoint, right? How come we get an HTTP/2 related error when invoking the action?

**Comment by tripodsan** [comment]
I looked at our logs some more and filtered out all the activations that showed this error. then I cross referenced them with the container uuid and found that all were on the same container.

so I revise my statement above and think that indeed, that the DNS change invalidated the HTTP/2 session which didn't get purged from _some_ cache in helix-fetch. this also explains why a redeploy solved the problem for good and could not be reproduced.

**Comment by tripodsan** [comment]
added issue in helix fetch
https://github.com/adobe/helix-fetch/issues/103
