### ISSUE TITLE
content-proxy requires ref

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-content-proxy#200]
Required for https://github.com/adobe/helix-pages/issues/531: `ref` might be undetermined when requesting the content-proxy (default branch must be used). The content-proxy must then:
- allow `ref` parameter to be omitted
- if this is the case, determine the `ref` (default branch) - should be responsibility of adobe/helix-resolve-git-ref. See adobe/helix-resolve-git-ref#287.

cc @trieloff @tripodsan

**Comment by kptdobe** [comment]
I am going to wait for adobe/helix-resolve-git-ref/issues/299 to change the behaviour here.

**Comment by tripodsan** [comment]
in https://github.com/adobe/helix-home/issues/187 it was decided that we always send a ref along.
so closing this.
