### ISSUE TITLE
Why does the content-proxy sometimes returns 202 ?

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-content-proxy#202]
Check this activation id: c978ed8cecea428db8ed8cecea928d36 (https://experience.adobe.com/#/@helix/custom-apps/325368-TraceDebug/#c978ed8cecea428db8ed8cecea928d36)

Why does it return a 202 ?

**Comment by trieloff** [comment]
Adobe I/O returns a 202 when the response to a web action cannot be determined within 60 seconds. As our own limit is 60 seconds, this typically happens when queueing time gets too long.
