### ISSUE TITLE
File not Found errors from resolve bubble up to epsagon

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#211]
**Description**
if a resolve of a google doc results in a 404, the error is not cought in the action but bubbles up to epsagon:

![image](https://user-images.githubusercontent.com/917628/99325668-2b467d00-28ba-11eb-8901-3a1ed8a846cd.png)

**Comment by rofe** [comment]
It still happens for this gdrive URL:
![image](https://user-images.githubusercontent.com/1609742/99566406-245c5f00-29cd-11eb-9496-8b243ef2dcc3.png)

**Comment by tripodsan** [comment]
yes. it seems like this is a request to an old content proxy v1.13.19, probably from an old bookmarklet.
