### ISSUE TITLE
add "lookup" feature for preview links

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-content-proxy#212]
currently there is a "reverse" lookup that triggers a redirect #126 for a given document id to a preview (inner CDN) URL
it would be great if the same functionality existed the other way around with a redirect to the authoring experience, this would allow us to place an "edit" button into the the sidekick for preview links.

**Comment by tripodsan** [comment]
usage:

```
https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v2?repo=theblog&owner=adobe&ref=master&path=/&edit=https://theblog--adobe.hlx.page/en/publish/2020/11/09/adobe-to-acquire-workfront.html
```

notes:
- currently `repo`, `owner`, `ref`, `path` is still needed. it _would_ be possible to infer this from the url in `edit`.
- `path` is not used. but it's a mandatory property. :-)
- the hostname in `edit` is not used. so it's possible to also pass in an outer-cdn url (as long as the url space mapping is identical to the one in the inner-cdn)

**Comment by rofe** [comment]
Very cool!
