### ISSUE TITLE
Add option to retrieve Lookup Info

### ISSUE THREAD

**Issue by rofe** [adobe/helix-content-proxy#227]
**Description**
The lookup URL fom the `_taxonomy.xlsx` is missing the `_` prefix and therefore giving a `404`.

`https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v2?owner=adobe&repo=theblog&ref=master&path=%2F&lookup=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FTheBlog%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B565E00D2-2D27-44B2-9DDA-35D182F0F698%257D%26file%3D_taxonomy.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue`

**To Reproduce**
1. Go to `https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v2?owner=adobe&repo=theblog&ref=master&path=%2F&lookup=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FTheBlog%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257B565E00D2-2D27-44B2-9DDA-35D182F0F698%257D%26file%3D_taxonomy.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue`
4. Observe URL: https://theblog--adobe.hlx.page/en/topics/taxonomy.json (404)

**Expected behavior**
URL should be https://theblog--adobe.hlx.page/en/topics/_taxonomy.json

**Comment by tripodsan** [comment]
hmm... lookup applies to author-friendly url transformation, and removes the `_`. rather think, that the problem is, that author friendly resolution doesn't work for xls.

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-content-proxy/issues/229

**Comment by rofe** [comment]
@tripodsan #229 doesn't fully solve my problem because I'd need the exact URL, not the author-friendly one...

As discussed, I think it would be great to have a mode where content-proxy returns a 200 response with a json object containing both the exact and the author-friendly URL.
