### ISSUE TITLE
Author friendly document names doesn't work for json

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#229]
**Description**
The urls that resolve to spreadsheets are do not support author friendly urls.

**To Reproduce**
requesting https://theblog--adobe.hlx.page/en/topics/taxonomy.json results in a 404, since the real document's name is `_taxonomy.xslx`.

**Expected behavior**
The data is returned.

**Comment by rofe** [comment]
Maybe we could leave `_` if they are prefixed, assuming the user knows what they're doing?

**Comment by tripodsan** [comment]
well, both should work:

https://theblog--adobe.hlx.page/en/topics/taxonomy.json 
https://theblog--adobe.hlx.page/en/topics/_taxonomy.json
