### ISSUE TITLE
Make Caching Dependent on presence of helix-bot

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#34]
Related to https://github.com/adobe/helix-publish/issues/452: if the `helix-bot` has access to the repository, then we can treat all resources that are served with a branch name instead of a proper ref as indefinitely shared cacheable (not browser cacheable).

@tripodsan how hard would it be to check the install status of the bot for each repository?

**Comment by tripodsan** [comment]
the https://github.com/adobe/helix-bot-action-config can do this - but it needs github token.
But I think the extra request to check if the bot is installed (and properly set up to invalidate fastly) is as expensive  as calling git-resolve-ref.

In any case, using indefinite caching only helps for production, but for authoring/development, the raw.github side will still be up to 5 minutes cached.

what about using aio-lib-state (or another DB):
- content-proxy checks the _ref-cache_ DB if there is a sha for the current branch and if it's not too old.
- if there is no sha or if too old, serve the resource from the branch
- when the bot invalidates fastly, it also writes the latest SHA into the _ref-cache_ DB.

**Comment by trieloff** [comment]
If we cache the call to `helix-bot-action-config` once per repo, it should be fast enough. That way we won't need another database.

The dependence on a GitHub token is unfortunate, so that might necessitate the introduction of a database. `helix-bot-action-config` would store a list of known repos when writing and would allow (unauthenticated) checks for the existence of a single entry from the database.

Alternatively, could we use @dominique-pfister's observation database? Knowing that there is an observation listener on the repository is as good as knowing the bot has been installed.

(We wouldn't be leaking any confidential information, as you can guess the observation state from the response headers anyway)

**Comment by tripodsan** [comment]
> The dependence on a GitHub token is unfortunate, 

I think we can tell if the bot is installed w/o using the token. but we can't read the bot config to check if it is setup correctly to actually invalidate fastly.

> Alternatively, could we use @dominique-pfister's observation database? Knowing that there is an observation listener...

same here. we don't know if it's configured correctly.

---

anyways. the entire observation/flushing is different for helix _proper_ and helix-pages.
if the helix bot is installed on a helix-pages repository, then the cache is flushed automatically. no extra setup needed (AFAICR).

IMO, the advantage of a global `ref-cache` would be that:
- it is global :-) so we can build multiple tools to keep it update
- it can resolve sha's of private repositories w/o special credentials (I think)
- it doesn't rely on a multitude of assumptions on how the cache might be flushed
