### ISSUE TITLE
Google and Word should be cached forever

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#35]
Google and Word currently have a time-based cache, but we can treat at least the Shared-Cache `surrogate-control` as `immutable`, because they will be invalidated on the fastly level by the two bots.

**Comment by tripodsan** [comment]
but currently, they are not invalidated. it will take some time to implement this.
for word2md we already have the listener infrastructure in place, but not for gdocs.

**Comment by trieloff** [comment]
Do we have issues that we can link, so we don't built it before the invalidator is there?

**Comment by tripodsan** [comment]
> Do we have issues that we can link, so we don't built it before the invalidator is there?

not really. what's needed:

- create a dev-tool/admin to create onedrive subscriptions (partially done)
- create some automation to listen on fstab changes and create the subscriptions
- create a dev-tool/admin to create the observation topic
- create some automation to link the onedrive-listeners to the topics
- add a observation listener that invalidates the fastly based on the changes
- add some tooling that can setup the listener with the correct fastly credentials and subscribe it to the correct topic
- implement the google-drive listener and send events to the observation queue

also, the helix-pages use-case is still a bit vague and more complicated
- adding a helix-query.yaml should just _work_ (w/o adding a helix-bot, i guess)
- adding as fstab.yaml should just _work_ and start invalidating fastly (w/o adding a helix-bot, I guess)

@dominique-pfister maybe we should start a new issue in helix-home and track the steps needed to complete the entire observation/indexing/purging story.

**Comment by tripodsan** [comment]
I started a document here: https://github.com/adobe/helix-home/issues/129

**Comment by tripodsan** [comment]
I also created a project https://github.com/orgs/adobe/projects/10 for all observation-related topics.
