### ISSUE TITLE
multi user support

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#376]
**Description**
The current solution uses the same configured account for accessing the backend storages. it should be possible to
use different users, depending on the backend.

as a first step, for accessing private backends, it should use an alternate user if a GITHUB_TOKEN is specified.
in order for downstream services to use the correct user, the access token should be passed along (eg https://github.com/adobe/helix-word2md/issues/637, https://github.com/adobe/helix-data-embed/issues/335)

**Limitations**

- only 1 additional user account is used
- only sharepoint support

**Comment by tripodsan** [comment]
## (better) alternative

to overcome this limitation, @trieloff  suggested to store symmetric encrypted credentials in the fstab.
the encryption should be done with the `GITHUB_TOKEN` that is used to access the (private) repository.

the credentials can be username:password pairs, or even oauth refresh tokens. 

**format**

fstab.yaml:

```
mountpoints:
  /:
    url: https://adobe.sharepoint.com/sites/TheBlog/Shared%20Documents/theblog
    credentials: ...
```

```
credentials = aes256(`username=${user}&password${pass}`, GITHUB_TOKEN)
```

```
credentials = aes256(`refresh=${token}`, GITHUB_TOKEN)
```

**Comment by trieloff** [comment]
Related: https://github.com/adobe/helix-publish/pull/832 allows site-specific github tokens (the outer CDN would provide the token)

**Comment by tripodsan** [comment]
> Related: [adobe/helix-publish#832](https://github.com/adobe/helix-publish/pull/832) allows site-specific github tokens (the outer CDN would provide the token)

see the comments in the PR... I don't think this is a good idea. otherwise you can't use `*.pages` at all, without hacking your browser with a secret that nobody should know :-)

**Comment by trieloff** [comment]
The `credentials` field should be a list, so that in case of key rotation, multiple tokens can be used. When decrypting, we'd discard all credential values that are not a valid `username=${user}&password${pass}` string.
