### ISSUE TITLE
Changes to reverse resolver break sidekick

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#382]
See https://github.com/adobe/helix-content-proxy/pull/379/files#diff-41629dcc63276d799267ad24df29f434d9d5ebc007a00350f6cd839200b85e42L43-L54

This change in #379 (in anticipation of https://github.com/adobe/helix-home/issues/187) causes the sidekick in `spark-website` to break - see https://github.com/adobe/spark-website/pull/121#pullrequestreview-637017545 for a workaround.

See https://cq-dev.slack.com/archives/C01F5TQV0SF/p1618510521096600 for end-user bug report.

**Comment by tripodsan** [comment]
sorry for that. but let's fix sidekick....

**Comment by rofe** [comment]
> sorry for that. but let's fix sidekick....

I consider this a new feature 😉  See https://github.com/adobe/helix-pages/pull/867
