### ISSUE TITLE
CORS issue due to invalid access-control-allow-origin header

### ISSUE THREAD

**Issue by rofe** [adobe/helix-content-proxy#407]
Recent changes (likely #399) have introduced a bug that is breaking the Blog's custom plugin which is fetching the lookup report to be able to purge the json directly from sharepoint. Here's the browser console output:
`Access to fetch at 'https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v2?report=true&owner=adobe&repo=theblog&ref=master&path=%2F&lookup=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FTheBlog%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BB20BA4A8-5040-40DA-A19C-BAD381543FB6%257D%26file%3Dredirects.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3D5682fe56-f45b-4aeb-abd0-31583cdd6f4f' from origin 'https://adobe.sharepoint.com' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*,https://adobe.sharepoint.com', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
It can be reproduced with the following curl command:
```sh
curl -v https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v2\?report\=true\&owner\=adobe\&repo\=theblog\&ref\=master\&path\=%2F\&lookup\=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FTheBlog%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BB20BA4A8-5040-40DA-A19C-BAD381543FB6%257D%26file%3Dredirects.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3D5682fe56-f45b-4aeb-abd0-31583cdd6f4f -H 'Origin: https://adobe.sharepoint.com'
```
Response:
```
< access-control-allow-origin: *,https://adobe.sharepoint.com
< access-control-allow-methods: OPTIONS, GET, DELETE, POST, PUT, HEAD, PATCH,GET, HEAD, OPTIONS
```
Expected behavior:
If the `access-control-allow-origin` and `access-control-allow-methods` headers are already set (by i/o runtime), don't add to them.

**Comment by tripodsan** [comment]
it's not the content proxy thats add the 2nd header....:

https://github.com/adobe/helix-content-proxy/blob/f41655fef1a608b81cbeb78281d63f6823cbe7b7/src/reverse.js#L80-L86

I suggest you use universal runtime instead of adobe i/o:

```
$ curl -sD - 'https://helix-pages.anywhere.run/helix-services/content-proxy@v2?report=true&owner=adobe&repo=theblog&ref=master&path=/&lookup=https%3A%2F%2Fadobe.sharepoint.com%2F%3Ax%3A%2Fr%2Fsites%2FTheBlog%2F_layouts%2F15%2FDoc.aspx%3Fsourcedoc%3D%257BB20BA4A8-5040-40DA-A19C-BAD381543FB6%257D%26file%3Dredirects.xlsx%26action%3Ddefault%26mobileredirect%3Dtrue%26cid%3D5682fe56-f45b-4aeb-abd0-31583cdd6f4f' -H 'Origin: https://adobe.sharepoint.com'
HTTP/2 200
content-type: application/json
access-control-allow-methods: GET, HEAD, OPTIONS
access-control-allow-origin: https://adobe.sharepoint.com
```
