### ISSUE TITLE
An invalid fstab.yaml causes a 500, should be a 502

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-content-proxy#463]
Pointing to a github repo with an invalid `fstab.yaml`, the following error is reported:
```
Unhandled error Error: data must NOT have additional properties
at MountConfig.validate (/var/task/index.js:11860:11)
at MountConfig.init (/var/task/index.js:11926:16)
at async main (/var/task/index.js:573111:21)
at async /var/task/index.js:574299:18
at async /var/task/index.js:14428:24
at async lambdaAdapter (/var/task/index.js:14589:22) Error: data must NOT have additional properties
```

This causes an unhandled error with a status code 500

**Comment by trieloff** [comment]
Probably not a 400, as the issue is not the request per se, but the server config, so maybe a 502

**Comment by dominique-pfister** [comment]
In order to detect these kind of errors, I'm wondering whether [SchemaDerivedConfig](https://github.com/adobe/helix-shared/blob/e185e0c079602793f3e665bb41da923f52dc4efc/packages/helix-shared-config/src/SchemaDerivedConfig.js#L69
) in helix-shared might throw an error that is better detectable than now:
```
  throw new Error(ajv.errorsText());
```
May be a specific error type (e.g. FetchError) or add some extra property (e.g. `code`)?

**Comment by trieloff** [comment]
https://github.com/adobe/helix-shared/blob/e185e0c079602793f3e665bb41da923f52dc4efc/packages/helix-shared-config/src/ConfigValidator.js#L43-L66

Has an example of getting more nicely formatted error messages, so it is definitely possible to add more context there.
