### ISSUE TITLE
QueryBuilder Params not supported

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#55]

**Comment by tripodsan** [comment]
do we really want to support query builder in the content proxy?
I find this a bit dangerous. maybe this should be solved via some kind of stored queries.

@davidnuescheler WDYT?

**Comment by trieloff** [comment]
David requested the feature, I just opened the issue.

**Comment by tripodsan** [comment]
LOL

**Comment by davidnuescheler** [comment]
i really only want the paging, also because of the response size limit. i agree that query builder params are not necessary (at least for now) and possibly dangerous... 
i would probably prefer some more friendly params like `limit=` and `offset=`.

**Comment by davidnuescheler** [comment]
looks great... should this already be working on helix pages?
right now it still seems to ignore the limit and offset as far as i can tell... 
https://theblog-adobe.hlx.page/en/query-index.json?limit=5

**Comment by trieloff** [comment]
https://github.com/adobe/theblog/issues/213#issuecomment-645668995

> particularly for author pages and sparse topics we may want to revisit the approach, by either using server-sided filters or possibly just produce a "load posts" if the author hasn't written anything in a long time (let's say the last 1000 posts)

This means me need to pass through all `hlx_` parameters
