### ISSUE TITLE
static json from github doesn't seem to be delivered as expected

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-content-proxy#57]
i tried to develop with the `.json` representation of an excel spreadsheet locally with the helix-cli and due to #56 i wasn't able to, so i quickly copied the output of 

https://excel-index--theblog--adobe.hlx.page/en/query-index.json

into a `query-index.json` in the root of the repo and changed the path in my fetch from `/en/query-index.json` to `/query-index.json` which worked beautifully locally... however when i pushed it into my branch i am getting a 404 for that resource...

https://excel-index--theblog--adobe.hlx.page/query-index.json

while i can work around this for this instance, i am worried that this may be related to the content-proxy hijacking all `.json` requests, which obviously would break any helix pages site that is using json files in github.

**Comment by tripodsan** [comment]
currently, we have no fallback in place, in case the external provider can't provide the file.
see https://github.com/adobe/helix-content-proxy/issues/32  and https://github.com/adobe/helix-shared/issues/309

**Comment by davidnuescheler** [comment]
so would it be fair to say that this change would have broken all helix pages sites that were using `.json` files in their git repo and had a fstab mount for `/` to google drive or one drive?

**Comment by tripodsan** [comment]
I think so.

**Comment by tripodsan** [comment]
closing as won't fix.
