### ISSUE TITLE
Support Pretty URLs

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-content-proxy#7]
Ideally, `helix-content-proxy` should work like a drop-in-replacement to `https://raw.githubusercontent.com/`.

**Comment by tripodsan** [comment]
> Ideally, `helix-content-proxy` should work like a drop-in-replacement to `https://raw.githubusercontent.com/`.

I don't think this is a good idea...since `raw.githubusercontent.com`.... unless the content-proxy redirects to it eventually.

@davidnuescheler what is your take on this?

**Comment by tripodsan** [comment]
I think this works already when the fstab allows it.
