### ISSUE TITLE
Caching in content proxy

### ISSUE THREAD

**Issue by davidnuescheler** [adobe/helix-content-proxy#72]
## Overview
we currently seem to have an ad-hoc set of caches used in content proxy, which makes it very hard to get an expected result

## Details
there is a range of caches from the path to id resolution, helix-fetch, fstab, etc. that lead to many situations where content gets stuck in content proxy and changes in google drive / one drive are not reflected immediately

## Proposed Actions
for now i would recommend to err on the side of consistency vs. performance, meaning probably to suppress caches at this stage unless we can guarantee flushes on edit or we feel that there are very few changes

**Comment by rofe** [comment]
Now that we have the content proxy cache in Fastly, we should disable all others.

**Comment by rofe** [comment]
See #291
