### ISSUE TITLE
Support mounting of documents

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-content-proxy#97]
**Is your feature request related to a problem? Please describe.**
It would be cool to be able to mount directly a document, eg:

```yaml
mountpoints:
  /index.md: https://adobe-my.sharepoint.com/personal/tripod_adobe_com/Documents/helix-content/sub/welcome.docx
  /en: https://adobe-my.sharepoint.com/personal/tripod_adobe_com/Documents/helix-content
  /data.json: https://adobe-my.sharepoint.com/personal/tripod_adobe_com/Documents/helix-content/cars.xlsx
```

this would allow to un-claim the `/` subtree and have proper fallbacks for other toplevel elements.
it could even be simplified to:

```yaml
mountpoints:
 /: https://adobe-my.sharepoint.com/personal/tripod_adobe_com/Documents/helix-content/sub/welcome.docx
```

which would internally be expanded to the `/index.md` form. this also has the advantage, that a new helix-pages site only needs 1 document to start with, using a document with an arbitrary name (eg. homepage.docx). 

/cc @davidnuescheler @trieloff

**Comment by trieloff** [comment]
I like this better than all previous ideas we had for fallbacks.
